name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Atur versi Node.js sesuai kebutuhan

      - name: Install dependencies
        run: npm install # Jika menggunakan npm, ubah sesuai manajer paket yang digunakan

      - name: Build project
        run: npm run build # Perintah build, sesuaikan dengan proyek Anda

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Sesuaikan dengan folder output build Anda
